name: Build Plugin

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Find pom.xml
        id: find-pom
        run: |
          echo "Searching for pom.xml..."
          POM_PATH=$(find . -name "pom.xml" | head -n 1)
          if [ -z "$POM_PATH" ]; then
            echo "❌ No pom.xml found"
            exit 1
          fi
          echo "✅ Found pom.xml at: $POM_PATH"
          echo "POM_DIR=$(dirname $POM_PATH)" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          cd $POM_DIR
          mvn -B package --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: ${{ env.POM_DIR }}/target/*.jar
