name: Build Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Unzip if needed
        run: |
          if [ -f "BrokeSMPV1-8-maven-fixed-pom.zip" ]; then
            unzip -o BrokeSMPV1-8-maven-fixed-pom.zip -d ./src || true
          fi

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml | tee build.log
        continue-on-error: false

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: BrokeSMP-Plugin
          path: target/*.jar

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
