name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Unzip project
        run: |
          unzip -o BrokeSMPV1-8-maven-fixed-pom.zip -d project
          ls -R project

      - name: Build with Maven
        working-directory: project
        run: mvn -B package --file pom.xml
