name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Unzip project (if needed)
      run: |
        if ls *.zip 1> /dev/null 2>&1; then
          echo "Found zip, extracting..."
          unzip -o *.zip -d .
        else
          echo "No zip found, skipping unzip."
        fi

    - name: Build with Maven
      run: |
        mvn -B clean package || (echo "❌ Maven build failed!" && cat target/surefire-reports/*.txt || true && exit 1)

    - name: Upload built plugin
      uses: actions/upload-artifact@v3
      with:
        name: Plugin-JAR
        path: target/*.jar
