name: Build Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip '*.zip' -d ./srcdir
          ls -R ./srcdir

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd srcdir/*/
          mvn -B package | tee build.log

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: BrokeSMP-Plugin
          path: srcdir/*/target/*.jar

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: srcdir/*/build.log
